version: '3.8'

services:
  # Backend PHP/Apache service
  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    container_name: fitzone-backend
    volumes:
      - ./backend:/var/www/html/backend
      - ./docker/backend/apache-config.conf:/etc/apache2/sites-available/000-default.conf
      - ./frontend/img:/var/www/html/img
    ports:
      - "8000:80"
    environment:
      - DB_HOST=database
      - DB_USER=fitzone_user
      - DB_PASS=fitzone_password
      - DB_NAME=fitzone_db
      - PHP_DISPLAY_ERRORS=1
    depends_on:
      - database
    networks:
      - fitzone-network

  # Frontend service with Nginx
  frontend:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    container_name: fitzone-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - fitzone-network
    depends_on:
      - backend

  # Database service
  database:
    image: mysql:8.0
    container_name: fitzone-database
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=fitzone_db
      - MYSQL_USER=fitzone_user
      - MYSQL_PASSWORD=fitzone_password
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/import-schema.sh:/docker-entrypoint-initdb.d/import-schema.sh
      - ./backend/database/fitzone_db.sql:/docker-entrypoint-initdb.d/fitzone_db.sql
      - fitzone-db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "fitzone_user", "-pfitzone_password"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fitzone-network

networks:
  fitzone-network:
    driver: bridge

volumes:
  fitzone-db-data: